#!/bin/bash

# Update Blog Post Description
# Replaces AI-generated description with professional disclosure

echo "🔧 Updating blog post description..."

cd /opt/fueltheaura-ai

# Backup the current file
cp premium_ai_system.py premium_ai_system.py.description_backup

# Update the description in premium_ai_system.py
sed -i 's/Premium health and wellness content generated by AI/Our content creation process uses automated research and writing technology under the supervision of the Fuel The Aura Audit System and human editors. Each article undergoes factual and readability review before publication./g' premium_ai_system.py

echo "✅ Updated blog post description"
echo ""
echo "🔄 Restarting content generation service..."
systemctl restart fueltheaura-ai.service

echo ""
echo "✅ All done! Future blog posts will use the new description."
echo ""
echo "📊 Check status with:"
echo "   systemctl status fueltheaura-ai.service"